# Generated by Django 4.1.4 on 2022-12-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='images',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='measurement',
        ),
        migrations.AddField(
            model_name='orders',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.design'),
        ),
        migrations.AddField(
            model_name='orders',
            name='invoice_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Canceled'), (2, 'Accepted'), (3, 'Paid'), (4, 'Shipped'), (5, 'Completed')], default=1),
        ),
    ]
